---
name: Build and Deploy (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy on Self-Hosted Runner
    runs-on: self-hosted  # Utilise un runner auto-hébergé

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show containeur
        run: docker ps -a || true

      - name: Stop and Remove Old Container
        run: |
          docker compose down -v || true

      - name: Remove Old images 
        run: |
          docker image prune -a -f || true

      - name: Remove Old Container
        run: |
          docker container prune -f || true
          
      - name: Run container
        run: |
          docker compose up -d || true
