---
name: Build and Deploy (Self-Hosted)

on:
  push:
  

jobs:
  deploy:
    name: Build and Deploy on Self-Hosted Runner
    runs-on: self-hosted  # Utilise un runner auto-hébergé

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout Code
        run: mkdir -p /home/student/actions-runner-wpress/_work/wordPress/wordPress/letsencrypt/

      - name: Show containeur
        run: docker ps -a || true

      - name: Stop and Remove Old Container
        run: |
          docker compose down -v || true

      - name: Remove Old Container
        run: |      
          CONTAINERS=$(docker ps -aq)  # Récupère les IDs des conteneurs arrêtés ou en cours
          if [[ -n "$CONTAINERS" ]]; then  # Vérifie si la variable contient des IDs
            echo "Stopping and removing containers: $CONTAINERS"
            docker stop $CONTAINERS || true
            docker rm $CONTAINERS || true
          else
            echo "No containers to remove."
          fi
        shell: bash


      - name: Remove Old images 
        run: |
          docker image prune -a -f || true
        
      - name: Run container
        run: |
          docker compose up -d || true

      - name: Check new containeur
        run: |
          docker ps -a || true
          ls -l ./letsencrypt || true
          ls /home/student/actions-runner-wpress/_work/wordPress/wordPress/letsencrypt/acme.json

