---
name: Build and Deploy (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy on Self-Hosted Runner
    runs-on: self-hosted  # Utilise un runner auto-hébergé

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop and Remove Old Container
        run: |
          docker compose down -v || true
          

      - name: Run container
        run: docker compose up -d 
